language: php
dist: trusty
php:
  - '7.1'
#  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --ignore-platform-reqs
  - composer dumpautoload -o -a

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email:
    - karsten.john.gerber@googlemail.com
