language: php
php:
  - '7.0'
  - '7.1'
#  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --ignore-platform-reqs
  - composer dumpautoload -o -a

script:
  - phpunit --coverage-clover=coverage.clover

notifications:
  email:
    - karsten.john.gerber@googlemail.com
